config-version: 2

name: 'salesforce_source'
version: '0.0.1'

require-dbt-version: [">=0.18.0", "<0.20.0"]

models:
  salesforce_source:
    tmp:
      enabled: false
    materialized: view

vars:
  salesforce_source:
    account: "{{ source('salesforce', 'account') }}"
    opportunity: "{{ source('salesforce', 'opportunity') }}"
    user: "{{ source('salesforce', 'user') }}"
    user_role: "{{ source('salesforce', 'user_role') }}"
    account_pass_through_columns: []
    opportunity_pass_through_columns: []
    user_pass_through_columns: []
