name: 'salesforce_source_integration_tests'
version: '1.0.0'
config-version: 2

profile: 'integration_tests'

vars:
  salesforce_source:
    salesforce_database: raw
    salesforce_schema: raw_fivetran_salesforce

clean-targets:
    - target
    - dbt_modules
